services:
  qmk:
    build: .
    image: keymaps-qmk:latest
    command: bash -c "
      qmk clean --all &&
      qmk generate-autocorrect-data -kb gmmk/pro/rev1/ansi -km benjamingehl /root/qmk_firmware/keyboards/gmmk/pro/rev1/ansi/keymaps/benjamingehl/autocorrection_dict.txt &&
      qmk compile -kb gmmk/pro/rev1/ansi -km benjamingehl &&
      cp -a /root/qmk_firmware/.build/. /root/build/"
    volumes:
      - ./build:/root/build
      - ./benjamingehl:/root/qmk_firmware/keyboards/gmmk/pro/rev1/ansi/keymaps/benjamingehl
