#pragma once

#ifdef RGB_MATRIX_ENABLE
    #define RGB_MATRIX_SLEEP
    #define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
    #define RGB_MATRIX_DEFAULT_HUE 23
    #define RGB_MATRIX_DEFAULT_SAT 255
    #define RGB_MATRIX_DEFAULT_VAL 255
#endif // RGB_MATRIX_ENABLE
